version: "3"
services:
  memcached:
    image: memcached:1.5-alpine
    env_file:
      - .env
    
  redis:
    image: redis:5.0-alpine
    env_file:
      - .env

  convertit:
     image: makinacorpus/convertit:latest
     env_file:
      - .env

  screamshotter:
     image: makinacorpus/screamshotter:latest
     env_file:
      - .env
   
  celery:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    volumes:
        - .:/app/src
    depends_on:
      - memcached
      - redis
    user: ${UID:-0}:${GID:-0}
    command: celery -A geotrek worker -c 1
    
  web:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8001}:8000"
    volumes:
      - ./var:/app/src/var
    depends_on:
      - memcached
      - redis
      - screamshotter
      - convertit
    user: ${UID:-0}:${GID:-0}

  api:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${API_PORT:-8002}:8000"
    volumes:
      - ./var:/app/src/var
    depends_on:
      - memcached
      - redis
    user: ${UID:-0}:${GID:-0}
