version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  codestyle:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - run: apt update
      - run: apt install -y python3-pip
      - checkout
      - run: pip3 install flake8
      - run: flake8 --exclude "" --ignore=E501,F403,F405 geotrek/settings
      - run: flake8 geotrek
      - run: test $(ls geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID | wc -l) -eq 0
  build:
    machine: true
    steps:
      - checkout
      - run: docker pull makinacorpus/geodjango:bionic-py2
      - run: make build
      - run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
      - run: docker tag geotrek:latest geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID
      - run: docker push geotrekce/circleci-admin:W$CIRCLE_WORKFLOW_ID
  test:
    machine: true
    environment:
      LANG: C.UTF-8
    steps:
      - run: docker-compose run web coverage run --parallel-mode ./manage.py test --settings=geotrek.settings.tests
  deploy:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - run: ./docker/deploy.sh
workflows:
  version: 2
  all:
    jobs:
      - codestyle
      - build
      - test:
          requires:
            - build
#      - test_nds
#          requires:
#            - build
      - deploy:
          requires:
            - codestyle
            - test
#            - test_nds
