name: Check deps

on:
  push:

env:
  DEBIAN_FRONTEND: noninteractive

permissions:
  contents: write

jobs:
  quality:
    name: Checking dependency graph
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # lint with minimal version supported (3.8 in 18.04)

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip wheel setuptools
          pip3 install -r requirements-dev.txt -U

      - name: Check dependency graph
        run: |
          pip-compile -q
          pip-compile -q requirements-dev.in

      - name: Verify dependency graph is ok
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
             requirements.txt
             requirements-dev.txt

      - name: Validating graph
        if: steps.verify-changed-files.outputs.files_changed == 'true' && github.actor != 'dependabot[bot]'
        run: |
          echo "Dependency file(s) changed: ${{ steps.verify-changed-files.outputs.changed_files }}"
          core.setFailed('Please add your new dependencies in setup.py and/or requirements-dev.in then run pip-compile to add them in requirements. (see docs/contribute/development)')

      - name: Dependabot commit dependencies
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          commit_message: Apply dependencies update by dependabot
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_author: dependabot[bot] <support@github.com>
