name: Documentation

on:
  push:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    container:
      image: python:3.6
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v2
      - name: Documentation in container
        run: |
          cd docs/
          pip install -r ./requirements.txt
          make html
